/*
 * This source file was generated by the Gradle 'init' task
 */
package view;

import javafx.application.Application;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Application.launch(TelaPrincipal.class, args);
    }
}
